from pathlib import Path
p=Path('index.html')
s=p.read_text()
assert '<!-- Revenue Execution Owner Website V18 -->' in s
s=s.replace('<!-- Revenue Execution Owner Website V18 -->','<!-- Revenue Execution Owner Website V19 -->',1)
s=s.replace('Three connected areas. Eight points where performance can break down.','Three connected areas. Thirteen points where performance can break down.',1)
old_market='''<button class="stage" data-i="0"><span class="n">01</span><b>Solution & Market Fit</b><small>Is the offer solving a valuable problem the market will pay to fix?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="1"><span class="n">02</span><b>ICP & Positioning</b><small>Are we targeting the right buyers with a message that matters?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="2"><span class="n">03</span><b>Demand Generation</b><small>Are we creating enough quality demand from the right market?</small><span class="explore">Explore →</span></button>'''
new_market='''<button class="stage" data-i="0"><span class="n">01</span><b>Solution & Market Fit</b><small>Is the offer solving a valuable problem the market will pay to fix?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="1"><span class="n">02</span><b>ICP & Positioning</b><small>Are we targeting the right buyers and positioned around problems they care about?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="2"><span class="n">03</span><b>Messaging</b><small>Is our messaging resonating with the right buyers and converting interest into conversations?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="3"><span class="n">04</span><b>Demand Generation</b><small>Are we creating enough quality demand from the right market?</small><span class="explore">Explore →</span></button>'''
assert old_market in s
s=s.replace(old_market,new_market,1)
old_sell='''<button class="stage" data-i="3"><span class="n">04</span><b>Engagement & Qualification</b><small>Are we creating real conversations and pursuing the right opportunities?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="4"><span class="n">05</span><b>Opportunity Management</b><small>Are qualified deals progressing with evidence, ownership and clear next steps?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="5"><span class="n">06</span><b>Deal Progression & Forecast Confidence</b><small>Can management see what is real, what is at risk and what will close?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="6"><span class="n">07</span><b>Commercials & Close</b><small>Are pricing, proposals and final decisions converting opportunity into revenue?</small><span class="explore">Explore →</span></button>'''
new_sell='''<button class="stage" data-i="4"><span class="n">05</span><b>Engagement & Qualification</b><small>Are we creating real conversations and pursuing the right opportunities?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="5"><span class="n">06</span><b>Opportunity Management</b><small>Are qualified deals progressing with evidence, ownership and clear next steps?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="6"><span class="n">07</span><b>Deal Inspection</b><small>Are sellers and managers inspecting deals consistently using the same evidence, risks and next-step standards?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="7"><span class="n">08</span><b>Deal Progression & Forecast Confidence</b><small>Can management see which deals are genuinely progressing, what is at risk and what will close?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="8"><span class="n">09</span><b>Commercials & Close</b><small>Are pricing, proposals and final decisions converting opportunity into revenue?</small><span class="explore">Explore →</span></button>'''
assert old_sell in s
s=s.replace(old_sell,new_sell,1)
old_customer='''<p>Make sure customers reach value quickly, stay, expand and become a stronger source of future growth.</p>
<button class="stage" data-i="7"><span class="n">08</span><b>Onboarding, Retention & Expansion</b><small>Are customers reaching value, renewing, expanding and becoming advocates?</small><span class="explore">Explore →</span></button>'''
new_customer='''<p>Make sure customers onboard well, realise value, stay and become a stronger source of future growth.</p>
<button class="stage" data-i="9"><span class="n">10</span><b>Onboarding</b><small>Are new customers reaching a successful start quickly, with clear ownership and handoffs?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="10"><span class="n">11</span><b>Customer Value Realisation</b><small>Are customers achieving the outcomes they bought for, quickly enough and consistently enough?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="11"><span class="n">12</span><b>Retention</b><small>Are we identifying and addressing churn risk early enough to protect recurring revenue?</small><span class="explore">Explore →</span></button>
<button class="stage" data-i="12"><span class="n">13</span><b>Expansion</b><small>Are we systematically identifying and converting credible growth opportunities in existing accounts?</small><span class="explore">Explore →</span></button>'''
assert old_customer in s
s=s.replace(old_customer,new_customer,1)
start=s.index('const stages=[')
end=s.index(']\nconst comdetail',start)+1
stages='''const stages=[
["Solution & Market Fit","Is the offer solving a valuable problem the market will pay to fix?","Weak solution value or weak market fit makes every downstream commercial activity harder.","Weak differentiation · unclear value · low urgency · poor proof","Lower conversion, longer sales cycles, more price pressure and wasted commercial effort.","Customer value, problem urgency, willingness to pay, proof and differentiation."],
["ICP & Positioning","Are we targeting the right buyers and positioned around problems they care about?","Strong commercial execution starts with choosing the right buyers and positioning the offer around problems they recognise as important.","Wrong accounts · weak persona fit · unclear positioning · low relevance","Acquisition effort is wasted, response quality falls and pipeline starts with the wrong opportunities.","ICP, buyer roles, use cases, problem priority, positioning and segment-level conversion."],
["Messaging","Is our messaging resonating with the right buyers and converting interest into conversations?","Messaging turns positioning into buyer-facing language that earns attention, creates relevance and gives people a reason to engage.","Generic claims · feature-led language · unclear outcomes · weak proof · low response","Good targeting still underperforms because buyers do not immediately understand why the conversation matters.","Value proposition, buyer language, problem framing, proof, calls to action and message-to-conversation conversion."],
["Demand Generation","Are we creating enough quality demand from the right market?","Growth becomes unpredictable when the business cannot create a reliable flow of quality buying interest.","Insufficient demand · weak channels · inconsistent activity · poor conversion","Pipeline starts too small, revenue becomes less predictable and sales compensates with low-quality activity.","Channels, campaigns, content, referrals, partners, inbound/outbound and demand-to-pipeline conversion."],
["Engagement & Qualification","Are we creating real conversations and pursuing the right opportunities?","The business needs both enough engagement and discipline to separate real opportunities from noise.","Low meeting conversion · weak follow-up · pipeline inflation · poor disqualification","Selling capacity is wasted, pipeline confidence falls and win rates suffer.","Targeting, engagement, buyer evidence, qualification quality and disqualification discipline."],
["Opportunity Management","Are qualified deals progressing with evidence, ownership and clear next steps?","Qualified opportunities still need structured progression toward a buyer decision.","Stalled deals · ageing pipeline · unclear next actions · weak ownership","Sales cycles lengthen, deals slip and revenue is delayed or lost.","Stage progression, next actions, buyer commitments, ageing and ownership."],
["Deal Inspection","Are sellers and managers inspecting deals consistently using the same evidence, risks and next-step standards?","Deal inspection creates a shared management discipline for testing opportunity quality, exposing risk and agreeing what must happen next.","Opinion-based reviews · inconsistent criteria · missing evidence · late risk discovery · weak follow-through","Pipeline becomes inflated, coaching is inconsistent, risks surface too late and forecast quality deteriorates.","Inspection criteria, required evidence, review cadence, seller/manager roles, risk identification and action follow-up."],
["Deal Progression & Forecast Confidence","Can management see which deals are genuinely progressing, what is at risk and what will close?","Owners need reliable forward visibility based on how opportunities are actually progressing, not seller optimism alone.","Repeated slippage · weak stage evidence · stale close dates · optimistic commits · late surprises","Poor visibility creates revenue misses, weak resource decisions and late management intervention.","Stage-to-stage conversion, forecast logic, close-date integrity, slippage, coverage and forecast accuracy."],
["Commercials & Close","Are pricing, proposals and final decisions converting opportunity into revenue?","Late-stage commercial friction can destroy value created throughout the selling process.","Weak proposals · discount leakage · terms friction · late-stage loss","Margin erodes, decisions slow and otherwise winnable deals are lost.","Proposal quality, pricing, discounts, terms, negotiation, win/loss and close conversion."],
["Onboarding","Are new customers reaching a successful start quickly, with clear ownership and handoffs?","A strong customer relationship begins with a controlled handoff from sale to delivery and a fast path to first value.","Poor handoffs · slow implementation · unclear ownership · repeated customer effort · early friction","Time-to-value increases, confidence falls and avoidable churn risk begins immediately after the sale.","Sales-to-delivery handoff, onboarding workflow, ownership, milestones, customer effort and time-to-first-value."],
["Customer Value Realisation","Are customers achieving the outcomes they bought for, quickly enough and consistently enough?","Customer value realisation makes the promised commercial outcome visible and measurable after the sale.","Unclear success measures · low adoption · no outcome tracking · weak value reviews · poor proof","Retention weakens, references are harder to earn and expansion conversations lack evidence of delivered value.","Success outcomes, adoption, usage and outcome evidence, governance, value reviews and proof of realised value."],
["Retention","Are we identifying and addressing churn risk early enough to protect recurring revenue?","Retention depends on recognising changes in customer health before renewal risk becomes unavoidable.","Late risk detection · weak engagement · unresolved issues · renewal surprises · no save plan","Recurring revenue erodes, acquisition has to work harder and customer lifetime value falls.","Customer health, engagement, risk signals, renewal process, save actions, churn reasons and retention trends."],
["Expansion","Are we systematically identifying and converting credible growth opportunities in existing accounts?","Expansion turns proven customer value into additional revenue where there is a legitimate unmet need or wider use case.","No account growth plan · weak cross-sell visibility · reactive renewals · poor stakeholder coverage","Existing-customer revenue is underused and growth becomes overly dependent on new-logo acquisition.","Account potential, whitespace, stakeholder coverage, expansion triggers, opportunity creation and expansion conversion."]
]'''
s=s[:start]+stages+s[end:]
s=s.replace('showStage(2);','showStage(3);',1)
p.write_text(s)
